#!/bin/bash
# Author: Keith Walsh
# Date: 11/24/2023
# Class: IS 580-KB

########################
## Script Description ##
########################

# This is a STIG checker for 5 of the CAT 1 STIGs for Ubuntu 20.04. This script has been tested on Ubuntu 22.04 and works on Ubuntu 22.04. There is a second 
# script ("prep_stig.sh") that will make the 5 items in this STIG script non-compliant to start so you can test the detection and remediation of each of those
# STIG items. 
#
# This script will run a check on each item. It will report that an item is compliant if it is configured inline with the STIG guidance
# If an item is NOT Compliant, the script will inform the user and ASK if the user would like to fix the configuration. If the user responds with a 'y' or 'Y'
# the script will then make the item compliant. If ANY other entry is input, the script will SKIP that item and move to the next item.
#
#
# After action REPORT
#
# This Script is designed to clear all its activity and then print a final report that will check and relay the status of all script items following the 
# running of the script. If something is not working and a user needs to 'debug' the script the command 'clear' that appears right below the block of '#'
# can be removed to preserve the output of the script above the report 



#### MODIFICATION ####
# The STIG checklist tells the user to grep for the word 'telnetd' (and other items) only. If telnetd was never on the system, the return will be empty for 
# this command so this could work, however if telnet was ever on the system even if it has already been removed, the command from the STIG checklist WILL 
# return positive/TRUE because the entry is still in the compiter file. I adjusted the command to look for the double 'i' (or 'ii') preceeding telnetd as 
# this is the indicator that the application is installed from what i can tell. Once the application has been removed the system entry changes the 'ii' to 
# a 'rc'. modifying the command in this way has allowed me to test this script many times and prevent false positives.


############################
## STIG ID UBTU-20-010405 ##
############################
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "" # Provides spacing for readability
# This prints information to the user so that they know what STIG the script is checking
echo "Checking for the telnet package (STIG ID UBTU-20-010405)"
echo "" # Provides spacing for readability
# This if statement is running a check to see if telnetd is installed. dpkg -l lists the installed packages, then grep -q runs a search without showing output
if dpkg -l | grep -q "ii  telnetd"; then 
    # this sets the telnetd variable to "true" if the query above is met (the search phrase is found in the dpkg list output)
    telnetd=true
else
    # The esle statement catches everything that is not true and marks the telnetd variable to false 
    telnetd=false
fi # This ends the if statement

# The below if statment looks at the value of the telnetd vairable that was assigned above. if it is set to true then telnetd is on the system and we echo statments to let
# the user know it was found. then we prompt the user to ask if they want to remove the application
if [ "$telnetd" == true ]; then
    echo "❌ - telnetd was found on this system."
    echo "Do you want to remove the telnetd application to make the system compliant? (y,n)"
    read response1 # this is the variable that holds the user input to check if the script should resolve the item
    # The if statement reacts to the user input.  if the user uses an upper or lower case "y" then it will procede to removing the application
    if [[ "$response1" =~ ^[Yy]$ ]]; then
        echo "########################"
        echo "# Removing telnetd now #" # this is just information output for the user. this does not do anything to the system
        echo "########################"
        # The below command is the command that removes telnetd. the "-y prevents the user from needing to confirm the command. it auto-selects 'yes'"
        # The '&>' redirects the output on the screen to /dev/null. this keeps the screen from printing all the removal printouts keeping the script output clean for the user.
        sudo apt remove telnetd -y &> /dev/null
    else
        # This is a print statement that informs the user that they did not select to remove the telnetd app/service
        echo "Leaving telnetd installed. This STIG is not compliant and will need to be documented as such"
    fi
else
    # 
    echo "✅ - telnetd was not found on this system. This STIG Item is compliant."

fi

############################
## STIG ID UBTU-20-010406 ##
############################

echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "" # Provides spacing for readability
echo "Checking for the rsh-server package (STIG ID UBTU-20-010406)" # output for user awareness
echo "" # Provides spacing for readability

# this if statement is checking to see if the rsh-server software is installed on the system. if it is then the rsh_server value is set to true
if dpkg -l | grep -q "ii  rsh-server"; then
    rsh_server=true
else
    rsh_server=false # if the software is not found on the system, the rsh_server value is set to false
fi

# if the rsh_server value is set to true then it will use this if statement to let the user know and prompt for user input to resolve the issue
if [ "$rsh_server" == true ]; then
    echo "❌ - rsh-server was found on this system." # this is a clear identifier printed to the user that this item is NOT compliant
    echo "Do you want to remove the rsh-server application to make the system compliant? (y,n)" # this is the prompt for the user to let them know their choice for resolution
    read response2 # this is the variable that holds the user input to check if the script should resolve the item
    if [[ "$response2" =~ ^[Yy]$ ]]; then # this checks the users input to see if the script should resolve the issue or not
        echo "###########################"
        echo "# Removing rsh-server now #" # this is to inform the user that the software will be removed (if the user had selected this option)
        echo "###########################"
        sudo apt remove rsh-server -y &> /dev/null # this is the actual command to remove the software
    else
        echo "Leaving rsh-server installed. This STIG is not compliant and will need to be documented as such" # output for user awareness
    fi
else
    echo "✅ - rsh-server was not found on this system. This STIG Item is compliant." # output for user awareness
fi

############################
## STIG ID UBTU-20-010460 ##
############################

echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "" # Provides spacing for readability
echo "Checking for ctrl-alt-del.target status (STIG ID UBTU-20-010460)" # output for user awareness
echo "" # Provides spacing for readability

# this if statment is checking to see if the setting is compliant or not and then setting the value of the "ctrl_alt_del" variable based on results
if sudo systemctl status ctrl-alt-del.target | grep -q -e "Loaded: loaded" -e "Loaded: loaded"; then
    ctrl_alt_del=true
else
    ctrl_alt_del=false
fi

# this if statement will inform the user if the setting is not compliant and then prompt the user with the option to resolve this setting
if [ "$ctrl_alt_del" == true ]; then
    echo "❌ - ctrl-alt-del.target is not properly set on this system."  # output for user awareness
    echo "Would you like to change this setting to make the system compliant? (y,n)" # this is the prompt for the user to let them know their choice for resolution
    read response3 # this is the variable that holds the user input to check if the script should resolve the item
    if [[ "$response3" =~ ^[Yy]$ ]]; then # this checks the users input to see if the script should resolve the issue or not
        echo "########################################"
        echo "# Updating the ctrl-alt-del.target now #" # output for user awareness
        echo "########################################"
        sudo systemctl disable ctrl-alt-del.target &> /dev/null # this is the actual command to remove the setting. the &> /dev/null to to remove cli output to the user to make the script cleaner
        sudo systemctl mask ctrl-alt-del.target &> /dev/null # this is the actual command to remove the setting. the &> /dev/null to to remove cli output to the user to make the script cleaner
        sudo systemctl daemon-reload # this is the actual command to remove the setting. 
    else
        echo "Leaving ctrl-alt-del.target misconfigured. This STIG is not compliant and will need to be documented as such" # output for user awareness
    fi
else
    echo "✅ - ctrl-alt-del.target correctly set on this system. This STIG Item is compliant." # output for user awareness
fi

############################
## STIG ID UBTU-20-010463 ##
############################

# Description
#
echo "" # Provides spacing for readability
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+ Checking for the ability to use blank passwords (STIG ID UBTU-20-010463) +" # output for user awareness
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "" # Provides spacing for readability

# this checks the setting to see if the vlaue is compliant and assigns the variable to true if the nullok word is in the file making this compliant. otherwise the value is assigned false
if grep -q nullok /etc/pam.d/common-password; then
    nullok=true
else
    nullok=false
fi

# this if statement will inform the user if the setting is not compliant and then prompt the user with the option to resolve this setting
if [ "$nullok" == true ]; then
    echo "❌ - Blank passwords are currently allowed on this system." # output for user awareness
    echo "Would you like to change this setting to make the system compliant? (y,n)" # this is the prompt for the user to let them know their choice for resolution
    read response4 # this is the variable that holds the user input to check if the script should resolve the item
    if [[ "$response4" =~ ^[Yy]$ ]]; then
        echo "#########################################"
        echo "# Updating the password requirement now #" # output for user awareness
        echo "#########################################"
        sudo sed -i 's/nullok//g' /etc/pam.d/common-password # this is the actual command to remove the setting.
    else
        echo "Preventing blank passwords is misconfigured. This STIG is not compliant and will need to be documented as such" # output for user awareness
    fi
else
    echo "✅ - The blank password restriction is correctly set on this system. This STIG Item is compliant." # output for user awareness
fi

############################
## STIG ID UBTU-20-010042 ##
############################

# Description
#
echo "" # Provides spacing for readability
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+ Checking for the SSH packages (STIG ID UBTU-20-010042) +" # output for user awareness
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "" # Provides spacing for readability

found_ssh_client=false
found_ssh_server=false
found_ssh_sftp=false
found_openssh=false

if sudo dpkg -l | grep -q "ii  openssh-client"; then
    found_ssh_client=true
fi

if sudo dpkg -l | grep -q "ii  openssh-server"; then
    found_ssh_server=true
fi

if sudo dpkg -l | grep -q "ii  openssh-sftp-server"; then
    found_ssh_sftp=true
fi

if "$found_ssh_client" == true && "$found_ssh_server" == true && "$found_ssh_sftp" == true; then
    found_openssh=true
fi

if [ "$found_openssh" == false ]; then
    echo "❌ - The openssh package is not installed on this system (either in part or in entirety)." # output for user awareness
    echo "Would you like to change this setting to make the system compliant? (y,n)" # this is the prompt for the user to let them know their choice for resolution
    read response5 # this is the variable that holds the user input to check if the script should resolve the item
    if [[ "$response5" =~ ^[Yy]$ ]]; then
        echo "##################################"
        echo "# Installing the SSH package now #" # output for user awareness
        echo "##################################"
        sudo apt install openssh-client openssh-server openssh-sftp-server -y &> /dev/null  # this is the actual command to remove the setting.
        sudo systemctl enable sshd.service # this is the actual command to remove the setting.
        sudo systemctl restart sshd.service # this is the actual command to remove the setting.
    else
        echo "SSH is not installed to protect the confidentiality and integrity of transmitted information." # output for user awareness
        echo "This STIG is not compliant and will need to be documented as such" # output for user awareness
    fi
else
    echo "✅ - SSH is installed on this system. This STIG Item is compliant." # output for user awareness
fi

################################################################################################################################################
##############################################################################################################################################
############################################################################################################################################
##########################################################################################################################################
########################################################################################################################################
######################################################################################################################################
####################################################################################################################################
##################################################################################################################################
################################################################################################################################
##############################################################################################################################

##### REPORT #########

clear

echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo ""
echo " ii Final Report !!"
echo "Below are the final compliance status indicators for each"
echo "STIG item after making your selections with this script."
echo ""
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

##################################
# Final Report check for telnetd #
##################################
if dpkg -l | grep -q "ii  telnetd"; then
    telnetd=true
else
    telnetd=false
fi

if [ "$telnetd" == true ]; then
    echo "❌ - telnetd is NOT Compliant(STIG ID UBTU-20-010405)"
else
    echo "✅ - telnetd is Compliant (STIG ID UBTU-20-010405)"
fi
echo ""
#####################################
# Final Report check for rsh-server #
#####################################
if dpkg -l | grep -q "ii  rsh-server"; then
    rsh_server=true
else
    rsh_server=false
fi

if [ "$rsh_server" == true ]; then
    echo "❌ - rsh-server is NOT Compliant(STIG ID UBTU-20-010406)"
else
    echo "✅ - rsh-server is Compliant (STIG ID UBTU-20-010406)"
fi
echo ""
##############################################
# Final Report check for ctrl-alt-del.target #
##############################################
if sudo systemctl status ctrl-alt-del.target | grep -q -e "Loaded: loaded" -e "Loaded: loaded"; then
    ctrl_alt_del=true
else
    ctrl_alt_del=false
fi

if [ "$ctrl_alt_del" == true ]; then
    echo "❌ - ctrl-alt-del.target is NOT Compliant (STIG ID UBTU-20-010460)"
else
    echo "✅ - ctrl-alt-del.target is Compliant (STIG ID UBTU-20-010460)"
fi
echo ""
#################################
# Final Report check for nullok #
#################################
if grep -q nullok /etc/pam.d/common-password; then
    nullok=true
else
    nullok=false
fi

if [ "$nullok" == true ]; then
    echo "❌ - nullok is NOT Compliant (STIG ID UBTU-20-010463)"
else
    echo "✅ - nullok is Compliant (STIG ID UBTU-20-010463)"
fi
echo ""
##############################
# Final Report check for ssh #
##############################
# Here I reset all the variable back to false to ensure a clean check.
found_ssh_client=false
found_ssh_server=false
found_ssh_sftp=false
found_openssh=false

if sudo dpkg -l | grep -q "ii  openssh-clien"; then
    found_ssh_client=true
fi

if sudo dpkg -l | grep -q "ii  openssh-server"; then
    found_ssh_server=true
fi

if sudo dpkg -l | grep -q "ii  openssh-sftp-server"; then
    found_ssh_sftp=true
fi

if "$found_ssh_client" == true && "$found_ssh_server" == true && "$found_ssh_sftp" == true; then
    found_openssh=true
fi

if "$found_openssh" == true; then
    echo "✅ - ssh is Compliant (STIG ID UBTU-20-010042)"
else
    echo "❌ - ssh is NOT Compliant (STIG ID UBTU-20-010042)"
fi
